# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensagem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mensagem.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0emensagem.proto\"\xd0\x03\n\x08Mensagem\x12.\n\rtipo_operacao\x18\x01 \x01(\x0e\x32\x17.Mensagem.Tipo_operacao\x12\x1e\n\x05\x61luno\x18\x02 \x03(\x0b\x32\x0f.Mensagem.Aluno\x1a\xbe\x02\n\x05\x41luno\x12\x35\n\x0bmatriculado\x18\x01 \x01(\x0e\x32\x1b.Mensagem.Aluno.Matriculado:\x03SIM\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\x12\x11\n\tmatricula\x18\x04 \x01(\x05\x12\r\n\x05\x63urso\x18\x05 \x01(\t\x12\x13\n\x08semestre\x18\x06 \x01(\x05:\x01\x30\x12,\n\x06\x63\x61mpus\x18\x07 \x01(\x0e\x32\x16.Mensagem.Aluno.Campus:\x04\x42\x41GE\"\x1f\n\x0bMatriculado\x12\x07\n\x03NAO\x10\x00\x12\x07\n\x03SIM\x10\x01\"[\n\x06\x43\x61mpus\x12\x08\n\x04NULL\x10\x00\x12\x08\n\x04\x42\x41GE\x10\x01\x12\x0c\n\x08\x41LEGRETE\x10\x02\x12\x0f\n\x0bSAO_GABRIEL\x10\x03\x12\x0e\n\nURUGUAIANA\x10\x04\x12\x0e\n\nLIVRAMENTO\x10\x05\"3\n\rTipo_operacao\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06SELECT\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MENSAGEM_ALUNO_MATRICULADO = _descriptor.EnumDescriptor(
  name='Matriculado',
  full_name='Mensagem.Aluno.Matriculado',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NAO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIM', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=306,
  serialized_end=337,
)
_sym_db.RegisterEnumDescriptor(_MENSAGEM_ALUNO_MATRICULADO)

_MENSAGEM_ALUNO_CAMPUS = _descriptor.EnumDescriptor(
  name='Campus',
  full_name='Mensagem.Aluno.Campus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALEGRETE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAO_GABRIEL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URUGUAIANA', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIVRAMENTO', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=339,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_MENSAGEM_ALUNO_CAMPUS)

_MENSAGEM_TIPO_OPERACAO = _descriptor.EnumDescriptor(
  name='Tipo_operacao',
  full_name='Mensagem.Tipo_operacao',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=432,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_MENSAGEM_TIPO_OPERACAO)


_MENSAGEM_ALUNO = _descriptor.Descriptor(
  name='Aluno',
  full_name='Mensagem.Aluno',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matriculado', full_name='Mensagem.Aluno.matriculado', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nome', full_name='Mensagem.Aluno.nome', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idade', full_name='Mensagem.Aluno.idade', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matricula', full_name='Mensagem.Aluno.matricula', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curso', full_name='Mensagem.Aluno.curso', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='semestre', full_name='Mensagem.Aluno.semestre', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='campus', full_name='Mensagem.Aluno.campus', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MENSAGEM_ALUNO_MATRICULADO,
    _MENSAGEM_ALUNO_CAMPUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=430,
)

_MENSAGEM = _descriptor.Descriptor(
  name='Mensagem',
  full_name='Mensagem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tipo_operacao', full_name='Mensagem.tipo_operacao', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aluno', full_name='Mensagem.aluno', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MENSAGEM_ALUNO, ],
  enum_types=[
    _MENSAGEM_TIPO_OPERACAO,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=483,
)

_MENSAGEM_ALUNO.fields_by_name['matriculado'].enum_type = _MENSAGEM_ALUNO_MATRICULADO
_MENSAGEM_ALUNO.fields_by_name['campus'].enum_type = _MENSAGEM_ALUNO_CAMPUS
_MENSAGEM_ALUNO.containing_type = _MENSAGEM
_MENSAGEM_ALUNO_MATRICULADO.containing_type = _MENSAGEM_ALUNO
_MENSAGEM_ALUNO_CAMPUS.containing_type = _MENSAGEM_ALUNO
_MENSAGEM.fields_by_name['tipo_operacao'].enum_type = _MENSAGEM_TIPO_OPERACAO
_MENSAGEM.fields_by_name['aluno'].message_type = _MENSAGEM_ALUNO
_MENSAGEM_TIPO_OPERACAO.containing_type = _MENSAGEM
DESCRIPTOR.message_types_by_name['Mensagem'] = _MENSAGEM

Mensagem = _reflection.GeneratedProtocolMessageType('Mensagem', (_message.Message,), dict(

  Aluno = _reflection.GeneratedProtocolMessageType('Aluno', (_message.Message,), dict(
    DESCRIPTOR = _MENSAGEM_ALUNO,
    __module__ = 'mensagem_pb2'
    # @@protoc_insertion_point(class_scope:Mensagem.Aluno)
    ))
  ,
  DESCRIPTOR = _MENSAGEM,
  __module__ = 'mensagem_pb2'
  # @@protoc_insertion_point(class_scope:Mensagem)
  ))
_sym_db.RegisterMessage(Mensagem)
_sym_db.RegisterMessage(Mensagem.Aluno)


# @@protoc_insertion_point(module_scope)
